/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DatosSql.AgenteQuimicoDTO;
import Negocio.NGestionarAgenteQuimico;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import util.jTableModel;

/**
 *
 * @author oscar
 */
public class VGestionarAgenteQuimico extends javax.swing.JFrame {

    /**
     * Creates new form VGestionarAgenteQuimico
     */
    private NGestionarAgenteQuimico ngaq;
    private Object titulo[]={"Id","Nombre", "Clasificacion"};
    public VGestionarAgenteQuimico() {
        initComponents();
        this.ngaq=new NGestionarAgenteQuimico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Id = new javax.swing.JLabel();
        jTFid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFclasificacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableagentequimico = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jBnuevo = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBbaja = new javax.swing.JButton();
        jBlistar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Agente Quimico");

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        Id.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        Id.setText("Id");
        jPanel1.add(Id);

        jTFid.setEnabled(false);
        jPanel1.add(jTFid);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTFnombre);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Clasificacion");
        jPanel1.add(jLabel4);
        jPanel1.add(jTFclasificacion);

        jTableagentequimico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Clasificacion"
            }
        ));
        jScrollPane1.setViewportView(jTableagentequimico);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        jBnuevo.setText("Nuevo");
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        jPanel2.add(jBnuevo);

        jBmodificar.setText("Modificar");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(jBmodificar);

        jBbaja.setText("Dar de baja");
        jBbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbajaActionPerformed(evt);
            }
        });
        jPanel2.add(jBbaja);

        jBlistar.setText("Listar");
        jBlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistarActionPerformed(evt);
            }
        });
        jPanel2.add(jBlistar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        try {
            this.jTFid.setText(this.ngaq
                    .nuevoAgenteQuimico(this.jTFnombre.getText(),
                            this.jTFclasificacion.getText()).getId().toString());
            showMessage("Dato guardado", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception ex) {
            showMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        try {
            this.ngaq.modificarAgenteQuimico(Integer.valueOf(this.jTFid.getText()),this.jTFnombre.getText(),
                    this.jTFclasificacion.getText());
            showMessage("Datos modificados", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            showMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbajaActionPerformed
        try {
            this.ngaq.darDeBajaAgenteQuimico(Integer.valueOf(this.jTFid.getText()),this.jTFnombre.getText(),
                    this.jTFclasificacion.getText());
            showMessage("Datos eliminados", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            showMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBbajaActionPerformed

    private void jBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistarActionPerformed
        
        try {
            List listaAgenteQuimico=this.ngaq.listarTodos(/*this.jTFnombre.getText()*/);
            Object matriz [][]=new Object[listaAgenteQuimico.size()][3];
            int i=0;
            for (Object aq : listaAgenteQuimico) {
               i=listaAgenteQuimico.indexOf(aq);
                AgenteQuimicoDTO a=(AgenteQuimicoDTO) aq;
                matriz[i][0]=a.getId();
                matriz[i][1]=a.getNombre();
                matriz[i][2]=a.getClasificacion();
                settableListener();
            }
            this.jTableagentequimico.setModel(new jTableModel(titulo, matriz));
        } catch (Exception ex) {
            Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBlistarActionPerformed
     private void settableListener(){
        
        this.jTableagentequimico.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRowIndex=jTableagentequimico.getSelectedRow();
                if(selectedRowIndex>-1 && selectedRowIndex<jTableagentequimico.getModel().getRowCount()){
                    TableModel model= jTableagentequimico.getModel();
                    jTFid.setText( model.getValueAt(selectedRowIndex, 0).toString());
                    jTFnombre.setText((String) model.getValueAt(selectedRowIndex, 1));
                   jTFclasificacion.setText(model.getValueAt(selectedRowIndex, 2).toString());
                    
                }
            }
        });

    
    }
    private void showMessage(String mensaje, int type){
        JOptionPane.showMessageDialog(this, mensaje, "mensaje", type);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VGestionarAgenteQuimico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VGestionarAgenteQuimico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JButton jBbaja;
    private javax.swing.JButton jBlistar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFclasificacion;
    private javax.swing.JTextField jTFid;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTable jTableagentequimico;
    // End of variables declaration//GEN-END:variables
}
