/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DatosSql.PersonaDTO;
import DatosSql.TipoPersonaDTO;
import Negocio.NGestionarPersona;
import Negocio.NGestionarTipoPersona;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import util.jTableModel;

/**
 *
 * @author oscar
 */
public class VGestionarPersona extends javax.swing.JFrame {

    /**
     * Creates new form VGestionarPersona
     */
    private NGestionarPersona ngp;
    private NGestionarTipoPersona ngtp;
            
    public VGestionarPersona() throws SQLException, ClassNotFoundException {
        initComponents();
        ngtp=new NGestionarTipoPersona();
        ngp=new NGestionarPersona();
        initComoboBox();
    }
    private void initComoboBox() throws SQLException{
        Object[] listaTp=ngtp.listarTodos().toArray();
        this.jCBtipopersona.setModel(new DefaultComboBoxModel(listaTp));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersona = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFapellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFci = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFtelefono = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFempresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCBtipopersona = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Persona");

        jTablePersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Apellido", "C.I.", "Telefono", "Email", "Empresa", "Tip. Persona"
            }
        ));
        jScrollPane1.setViewportView(jTablePersona);

        jPanel1.setBorder(null);
        jPanel1.setLayout(new java.awt.GridLayout(8, 2));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Id");
        jPanel1.add(jLabel1);

        jTFid.setEnabled(false);
        jPanel1.add(jTFid);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jPanel1.add(jTFnombre);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3);
        jPanel1.add(jTFapellido);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("C.I.");
        jPanel1.add(jLabel5);

        jTFci.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(jTFci);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4);

        jTFtelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(jTFtelefono);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Email");
        jPanel1.add(jLabel8);
        jPanel1.add(jTFemail);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Empresa");
        jPanel1.add(jLabel6);
        jPanel1.add(jTFempresa);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("TipoPersona");
        jPanel1.add(jLabel7);

        jCBtipopersona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jCBtipopersona);

        jPanel2.setBorder(null);
        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Dar deBaja");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.ngp.nuevo(this.jTFnombre.getText(),
                    this.jTFapellido.getText(),
                    Integer.valueOf(this.jTFci.getText()),
                    Integer.valueOf(this.jTFtelefono.getText()),
                    this.jTFemail.getText(),
                    this.jTFempresa.getText(), (TipoPersonaDTO) this.jCBtipopersona.getSelectedItem());
            showMessage("Persona guardada!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            showMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VGestionarPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            this.ngp.modificar(
                    Integer.valueOf(this.jTFid.getText()),
                    this.jTFnombre.getText(),
                    this.jTFapellido.getText(),
                    Integer.valueOf(this.jTFci.getText()),
                    Integer.valueOf(this.jTFtelefono.getText()),
                    this.jTFemail.getText(),
                    this.jTFempresa.getText(), (TipoPersonaDTO) this.jCBtipopersona.getSelectedItem());
            showMessage("Persona Modificada", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            showMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VGestionarPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            this.ngp.darDeBaja(Integer.valueOf(this.jTFid.getText()),
                    this.jTFnombre.getText(),
                    this.jTFapellido.getText(),
                    Integer.valueOf(this.jTFci.getText()),
                    Integer.valueOf(this.jTFtelefono.getText()),
                    this.jTFemail.getText(),
                    this.jTFempresa.getText(), (TipoPersonaDTO) this.jCBtipopersona.getSelectedItem());
             showMessage("Persona Eliminada", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            showMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VGestionarPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            List lista=this.ngp.listarTodos();
            Object vector[]={"Id","Nombre","Apellido","C.I.","Telefono","Email","Empresa", "T. Persona"} ;
            Object matriz [][]=new Object[lista.size()][8];
            jTableModel model;
            if(lista!=null && !lista.isEmpty()){
                for (Object o1 : lista) {
                    int i=lista.indexOf(o1);
                    PersonaDTO tp=(PersonaDTO) o1;
                    matriz[i][0]=tp.getId();
                    matriz[i][1]=tp.getNombre();
                    matriz[i][2]=tp.getApellido();
                    matriz[i][3]=tp.getCi();
                    matriz[i][4]=tp.getTelefono();
                    matriz[i][5]=tp.getEmail();
                    matriz[i][6]=tp.getNombreEmpresa();
                    matriz[i][7]=tp.getTipoPersona();
                }
                model=new jTableModel(vector, matriz);
                this.jTablePersona.setModel(model);
                settableListener();
            } 
        }catch (Exception ex) {
            Logger.getLogger(VGestionarPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    private void settableListener(){
        
        this.jTablePersona.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRowIndex=jTablePersona.getSelectedRow();
                if(selectedRowIndex>-1 && selectedRowIndex<jTablePersona.getModel().getRowCount()){
                    TableModel model= jTablePersona.getModel();
                    jTFid.setText( model.getValueAt(selectedRowIndex, 0).toString());
                    jTFnombre.setText((String) model.getValueAt(selectedRowIndex, 1));
                    jTFapellido.setText(model.getValueAt(selectedRowIndex, 2).toString());
                    jTFci.setText(model.getValueAt(selectedRowIndex, 3).toString());
                    jTFtelefono.setText(model.getValueAt(selectedRowIndex, 4).toString());
                    jTFemail.setText(model.getValueAt(selectedRowIndex, 5).toString());
                    jTFempresa.setText(model.getValueAt(selectedRowIndex, 6).toString());
                    jCBtipopersona.setSelectedItem(model.getValueAt(selectedRowIndex, 7));
                    
                }
            }
        });

    
    }
    private void showMessage(String mensaje,int tipo){
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", tipo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VGestionarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VGestionarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VGestionarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VGestionarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VGestionarPersona().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(VGestionarPersona.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(VGestionarPersona.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jCBtipopersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFapellido;
    private javax.swing.JFormattedTextField jTFci;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFempresa;
    private javax.swing.JTextField jTFid;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JFormattedTextField jTFtelefono;
    private javax.swing.JTable jTablePersona;
    // End of variables declaration//GEN-END:variables
}
