/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.TipoPersona;
import Negocio.NGestionarTipoPersona;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import util.jTableModel;

/**
 *
 * @author oscar
 */
public class VTipoPersona extends javax.swing.JFrame {

    /**
     * Creates new form VTipoUsuario
     */
    private NGestionarTipoPersona ntp;
    public VTipoPersona() {
        initComponents();
        ntp=new NGestionarTipoPersona();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBGuardar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFdescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Tipo Persona");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(null);
        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        jBGuardar.setText("Nuevo");
        jBGuardar.setMaximumSize(new java.awt.Dimension(77, 29));
        jBGuardar.setMinimumSize(new java.awt.Dimension(77, 29));
        jBGuardar.setPreferredSize(new java.awt.Dimension(77, 29));
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGuardar);

        jBModificar.setText("Modificar");
        jPanel1.add(jBModificar);

        jBBuscar.setText("Buscar");
        jBBuscar.setMaximumSize(new java.awt.Dimension(77, 29));
        jBBuscar.setMinimumSize(new java.awt.Dimension(77, 29));
        jBBuscar.setPreferredSize(new java.awt.Dimension(77, 29));
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscar);

        jBEliminar.setText("Dar de baja");
        jBEliminar.setMaximumSize(new java.awt.Dimension(77, 29));
        jBEliminar.setMinimumSize(new java.awt.Dimension(77, 29));
        jBEliminar.setPreferredSize(new java.awt.Dimension(77, 29));
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar);

        jPanel2.setBorder(null);
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Id");
        jLabel1.setMaximumSize(new java.awt.Dimension(57, 17));
        jLabel1.setPreferredSize(new java.awt.Dimension(57, 17));
        jPanel2.add(jLabel1);

        jTFId.setEnabled(false);
        jTFId.setMinimumSize(new java.awt.Dimension(57, 27));
        jPanel2.add(jTFId);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2);
        jPanel2.add(jTFNombre);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Descripcion");
        jPanel2.add(jLabel3);
        jPanel2.add(jTFdescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        try {
            
            TipoPersona tp =ntp.guardarTipoPersona(jTFNombre.getText(),jTFdescripcion.getText());
            this.jTFId.setText(tp.getId().toString());
            ShowMessage("Dato guardado", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ShowMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        try {
            List lista=ntp.buscarTipoPersona(this.jTFNombre.getText());
            Object vector[]={"Id","Nombre","Descripcion"} ;
            Object matriz [][]=new Object[lista.size()][3];
            jTableModel model;
            if(lista!=null && !lista.isEmpty()){
                for (Object o1 : lista) {
                    int i=lista.indexOf(o1);
                    TipoPersona tp=(TipoPersona) o1;
                    matriz[i][0]=tp.getId();
                    matriz[i][1]=tp.getNombre();
                    matriz[i][2]=tp.getDescripcion();
                }
                model=new jTableModel(vector, matriz);
                this.jTable1.setModel(model);
                settableListener();
            }}catch (Exception ex) {
                ShowMessage(ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        try {
            // TODO add your handling code here:
            this.ntp.darDeBaja(Integer.valueOf(jTFId.getText()), jTFNombre.getText(),jTFdescripcion.getText());
            ShowMessage("Se elimino el dato", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ShowMessage("Error al eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed
    private void settableListener(){
        
        this.jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRowIndex=jTable1.getSelectedRow();
                if(selectedRowIndex>-1 && selectedRowIndex<jTable1.getModel().getRowCount()){
                   // TipoPersona tp=new TipoPersona();
                    jTFId.setText( jTable1.getModel().getValueAt(selectedRowIndex, 0).toString());
                    jTFNombre.setText((String) jTable1.getModel().getValueAt(selectedRowIndex, 1));
                }
            }
        });

    
    }
    private void ShowMessage(String mensaje,int tipo){
        JOptionPane.showMessageDialog(this, mensaje, "Error", tipo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VTipoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VTipoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VTipoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VTipoPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VTipoPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFdescripcion;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
