package Datos;
// Generated Sep 4, 2015 11:14:54 AM by Hibernate Tools 4.3.1

import interfaces.THibernateHelper;
import java.util.List;




/**
 * DetallePerito generated by hbm2java
 */
public class DetallePerito extends THibernateHelper implements java.io.Serializable {


     private Integer id;
     private NotaPerito notaPerito;
     private Servicio servicio;
     private Integer cantidad;
     private Float precioTotal;
      private long currentTransaction;

    public DetallePerito() {
        this.currentTransaction=0;
    }

    public DetallePerito(NotaPerito notaPerito, Servicio servicio, Integer cantidad, Float precioTotal) {
       this.notaPerito = notaPerito;
       this.servicio = servicio;
       this.cantidad = cantidad;
       this.precioTotal = precioTotal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public NotaPerito getNotaPerito() {
        return this.notaPerito;
    }
    
    public void setNotaPerito(NotaPerito notaPerito) {
        this.notaPerito = notaPerito;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Float getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Float precioTotal) {
        this.precioTotal = precioTotal;
    }

    @Override
    public List buscar() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Boolean eliminar() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object guardar(long transactionID) throws Exception {
        return guardarEntidad(this);
    }

    @Override
    public Object modificar() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    @Override
    public boolean join(long transactionID) {
        if(this.currentTransaction!=0){
            return false;
        }
        this.currentTransaction=transactionID;
        return true;
    }

    @Override
    public boolean commit(long transactionID) throws Exception {
         if(this.currentTransaction!=transactionID){
            System.out.println("id de transaccion equivocado");
            System.out.println("currentTransaction= "+this.currentTransaction);
            System.out.println("transactionID= "+transactionID);
            return false;
        }
        this.guardar(transactionID);
        return true;
    }

    @Override
    public boolean cancel(long transactionID) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object guardar() throws Exception {
        return guardarEntidad(this);
    }
}


